export const USERINFO_UPDATE = 'USERINFO_UPDATE';
export const SEARCHBOOK_UPDATE = 'SEARCHBOOK_UPDATE';
export const CHAPTER_UPDATE = 'CHAPTER_UPDATE';
export const GLOBAL_ROUTE_HISTORY = 'GLOBAL_ROUTE_HISTORY';
// export const CHAPTER_LOADING = 'CHAPTER_LOADING';